# Generated by Django 6.1.1 on 2026-10-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_per_doctor_slot',
        ),
    ]
